# Numpy

- General purpose array processing package
- provides high performance multi dimensional array
- need to install the numpy library seprately and we need to import

## Array
 - array is a data structure which stores the values with same datatype
 - there is a main difference between lists and arrays
 - in list we can store different datatypes but in array we can store only the same datatype
 - Array is an reference type

In [2]:
import numpy as np

In [3]:
my_lst = [1,2,3,4,5]

In [6]:
arr = np.array(my_lst)

In [7]:
type(arr)

numpy.ndarray

In [8]:
arr

array([1, 2, 3, 4, 5])

In [9]:
arr.shape

(5,)

# Multidimensional Array

- In Single dimensional array we have one open and close bracket []
- In two or multi dimensional array we have more than one []

In [10]:
my_lst1 = [1,2,3,4,5]
my_lst2 = [2,3,4,5,6]
my_lst3 = [3,4,5,6,7]

my_array = [my_lst1,my_lst2,my_lst3]

In [11]:
my_array

[[1, 2, 3, 4, 5], [2, 3, 4, 5, 6], [3, 4, 5, 6, 7]]

In [12]:
arr1 = np.array(my_array)

In [13]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [14]:
arr1.shape

(3, 5)

# Reshaping the array

- when reshaping the array you need to define the element count should match
- array values are represented as (rows, columns)
- you can reshape the array to single line like (1,10), but it is an multi dimensional array and contains [[]]
- for example, in the array you have 10 elements and the shape is (2,5) now you want to reshape the array to (3,3) while issuing the command it shows the error like cannot reshape array of size 10 into shape (3,3)

In [15]:
arr1.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 3, 4],
       [5, 6, 7]])

In [16]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [17]:
arr1.reshape(4,4)

ValueError: cannot reshape array of size 15 into shape (4,4)

# Indexing
 
 - Indexing starts from 0

In [18]:
my_array12 = ([1,2,3,4,5,6,7,8])

In [19]:
type(my_array12)

list

In [20]:
my_arr12 = np.array(my_array12)

In [21]:
my_arr12

array([1, 2, 3, 4, 5, 6, 7, 8])

In [22]:
my_arr12[2]

3

# Indexing for multi dimensional array

- indexing for multi dimension works on [row_start:row_until , column_start:column_until]

In [24]:
my_array

[[1, 2, 3, 4, 5], [2, 3, 4, 5, 6], [3, 4, 5, 6, 7]]

In [27]:
type(my_array)

list

In [29]:
my_array1 = np.array(my_array)

In [30]:
type(my_array1)

numpy.ndarray

In [31]:
my_array1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [32]:
my_array1[0:2,:]

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6]])

In [35]:
my_array1[1:,3:]

array([[5, 6],
       [6, 7]])

In [36]:
my_array1[1:,2:4]

array([[4, 5],
       [5, 6]])

In [37]:
my_array1[1:2,1:4]

array([[3, 4, 5]])

# Inbuilt functions
## use Shift + Tab to see the function syntax
- arrange
- reshape
- linspace
- copy
- np.ones
- np.random.rand
- np.random.randint


### Array is basically a reference type, ex: A2=A1 means the values in A1 will be referenced in A2 and if you are changing the value in A1 will be reflected in A2 and the value changes in A2 will be reflected in A1)


In [39]:
arr=np.arange(1,10)

In [40]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
arr1=np.arange(1,10,2)

In [42]:
arr1

array([1, 3, 5, 7, 9])

In [43]:
np.linspace(1,10,50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])